/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author truon
 */
public class main extends javax.swing.JFrame {

    private DefaultTableModel BNmodel;
    private DefaultTableModel BSmodel;
    private DefaultTableModel DTmodel;
    private DefaultTableModel Tmodel;
    private DefaultTableModel LTmodel;
    private DefaultTableModel Kmodel;
    private DefaultTableModel HDmodel;
    private DefaultTableModel BAmodel;
    public main() {
        initComponents();
        BNmodel = new DefaultTableModel();
        BSmodel = new DefaultTableModel();
        DTmodel = new DefaultTableModel();
        Tmodel = new DefaultTableModel();
        LTmodel = new DefaultTableModel();
        Kmodel = new DefaultTableModel();
        HDmodel = new DefaultTableModel();
        BAmodel = new DefaultTableModel();
        jTable1.setModel(BNmodel);
        table.loadData2(BNmodel);
        table.loadData1(BSmodel);
        table.loadData3(DTmodel);
        table.loadData4(Tmodel);
        table.loadData5(LTmodel);
        table.loadData6(Kmodel);
        table.loadData7(HDmodel);
        table.loadData8(BAmodel);
    }
    
    private void clearTextFields() {
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField7.setText("");
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bệnh Nhân", "Bác Sĩ", "Đơn Thuốc", "Thuốc, Dược Phẩm", "Khoa", "Loại Thuốc", "Bệnh Án", "Hóa Đơn" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Đăng xuất");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 102));
        jButton5.setText("Thống kê");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 51, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Thêm bệnh án");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã bệnh nhân", "Họ tên", "Giới tính", "Ngày sinh", "Địa chỉ", "SĐT", "Bảo hiểm y tế"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã bệnh nhân");

        jLabel2.setText("Họ tên");

        jLabel3.setText("Giới tịnh");

        jLabel4.setText("Ngày sinh");

        jLabel5.setText("Địa chỉ");

        jLabel6.setText("Số điện thoại");

        jLabel7.setText("BHYT");

        jPanel2.setBackground(new java.awt.Color(51, 255, 204));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Thêm bệnh nhân");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Tìm bệnh nhân");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Xóa bệnh nhân");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Nhập mã bệnh nhân:");

        jButton6.setBackground(new java.awt.Color(255, 255, 102));
        jButton6.setText("Tải lại");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField8)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         String buttonText = jButton2.getText();
        if (buttonText.equals("Thêm bác sĩ")) {
        // Lấy dữ liệu từ các JTextField cho Bác Sĩ
        String maBacSi = jTextField1.getText();
        String hoTen = jTextField2.getText();
        String gioiTinh = jTextField3.getText();
        String hocVi = jTextField4.getText();
        String chuyenMon = jTextField5.getText();
        String maKhoa = jTextField6.getText();

        // Gọi phương thức thêm bác sĩ từ lớp chứa phương thức thêm vào CSDL
        table.addBS(maBacSi, hoTen, gioiTinh, hocVi, chuyenMon, maKhoa);

        // Load lại dữ liệu vào bảng Bác Sĩ để cập nhật thông tin mới
        BSmodel.setRowCount(0); // Xóa dữ liệu hiện tại trong bảng
        table.loadData1(BSmodel);
        clearTextFields();
    } else if (buttonText.equals("Thêm bệnh nhân")) {
        // Lấy dữ liệu từ các JTextField cho Bệnh Nhân
        String maBenhNhan = jTextField1.getText();
        String hoTen = jTextField2.getText();
        String gioiTinh = jTextField3.getText();
        String ngaySinh = jTextField4.getText();
        String diaChi = jTextField5.getText();
        String sdt = jTextField6.getText();
        String baoHiemYTe = jTextField7.getText();

        // Gọi phương thức thêm bệnh nhân từ lớp chứa phương thức thêm vào CSDL
        table.addBN(maBenhNhan, hoTen, gioiTinh, ngaySinh, diaChi, sdt, baoHiemYTe);

        // Load lại dữ liệu vào bảng Bệnh Nhân để cập nhật thông tin mới
        BNmodel.setRowCount(0); // Xóa dữ liệu hiện tại trong bảng
        table.loadData2(BNmodel);
        clearTextFields();
    }
    else if (buttonText.equals("Thêm thuốc")) {
    // Lấy dữ liệu từ các JTextField cho Thuốc
    String maThuoc = jTextField1.getText();
    String tenThuoc = jTextField2.getText();
    int soLuong = Integer.parseInt(jTextField3.getText());
    double giaThuoc = Double.parseDouble(jTextField4.getText());
    String ngaySanXuat = jTextField5.getText();
    String hanSuDung = jTextField6.getText();
    String maLoaiThuoc = jTextField7.getText(); // Lưu ý: Bạn cần có JTextField cho ngày sản xuất và hạn sử dụng

    // Gọi phương thức thêm Thuốc từ lớp chứa phương thức thêm vào CSDL
    table.addThuoc(maThuoc, tenThuoc, soLuong, giaThuoc, ngaySanXuat, hanSuDung, maLoaiThuoc);

    // Load lại dữ liệu vào bảng Thuốc để cập nhật thông tin mới
    Tmodel.setRowCount(0); // Xóa dữ liệu hiện tại trong bảng
    table.loadData4(Tmodel);
    clearTextFields();
} else if (buttonText.equals("Thêm loại thuốc")) {
    // Lấy dữ liệu từ các JTextField cho Loại Thuốc
    String maLoaiThuoc = jTextField1.getText();
    String tenLoaiThuoc = jTextField2.getText();

    // Gọi phương thức thêm Loại Thuốc từ lớp chứa phương thức thêm vào CSDL
    table.addLoaiThuoc(maLoaiThuoc, tenLoaiThuoc);

    // Load lại dữ liệu vào bảng Loại Thuốc để cập nhật thông tin mới
    LTmodel.setRowCount(0); // Xóa dữ liệu hiện tại trong bảng
    table.loadData5(LTmodel);
    clearTextFields();
} else if (buttonText.equals("Thêm đơn thuốc")) {
    // Lấy dữ liệu từ các JTextField cho Khoa
    String maDonThuoc = jTextField1.getText();
    String soLuong = jTextField2.getText();
    String gia = jTextField3.getText();
    int maHoaDon = Integer.parseInt(jTextField4.getText());
    double maThuoc = Double.parseDouble(jTextField5.getText());;


    // Load lại dữ liệu vào bảng Khoa để cập nhật thông tin mới
    Kmodel.setRowCount(0); // Xóa dữ liệu hiện tại trong bảng
    table.loadData6(Kmodel);
    clearTextFields();
}   
        else if (buttonText.equals("Thêm khoa")) {
    // Lấy dữ liệu từ các JTextField cho Khoa
    String maKhoa = jTextField1.getText();
    String tenKhoa = jTextField2.getText();
    String moTa = jTextField3.getText();

    // Gọi phương thức thêm Khoa từ lớp chứa phương thức thêm vào CSDL
    table.addKhoa(maKhoa, tenKhoa, moTa);

    // Load lại dữ liệu vào bảng Khoa để cập nhật thông tin mới
    Kmodel.setRowCount(0); // Xóa dữ liệu hiện tại trong bảng
    table.loadData6(Kmodel);
    clearTextFields();
} 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selectedOption = jComboBox1.getSelectedItem().toString();

    // Kiểm tra và chuyển đổi giữa bảng bệnh nhân và bảng bác sĩ
    if (selectedOption.equals("Bệnh Nhân")) {
        jTable1.setModel(BNmodel);
        jLabel1.setText("Mã bệnh nhân");
        jLabel2.setText("Họ tên");
        jLabel3.setText("Giới tính");
        jLabel4.setText("Ngày sinh");
        jLabel5.setText("Địa chỉ");
        jLabel6.setText("Số điện thoại");
        jLabel7.setText("BHYT");
        jLabel8.setText("Nhập mã bệnh nhân");
        jButton2.setText("Thêm bệnh nhân");
        jButton3.setText("Tìm bệnh nhân");
        jButton4.setText("Xóa bệnh nhân");
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jTextField6.setVisible(true);
        jTextField7.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jTextField8.setVisible(true);
    } else if (selectedOption.equals("Bác Sĩ")) {
        jTable1.setModel(BSmodel);
        jLabel1.setText("Mã bác sĩ");
        jLabel2.setText("Họ tên");
        jLabel3.setText("Giới tính");
        jLabel4.setText("Học vị");
        jLabel5.setText("Chuyên môn");
        jLabel6.setText("Mã khoa");
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jTextField6.setVisible(true);
        jTextField7.setVisible(false);
        jLabel7.setText("");
        jLabel8.setText("Nhập mã bác sĩ");
        jButton2.setText("Thêm bác sĩ");
        jButton3.setText("Tìm bác sĩ");
        jButton4.setText("Xóa bác sĩ");
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jTextField8.setVisible(true);
    }
    else if (selectedOption.equals("Đơn Thuốc")) {
        jTable1.setModel(DTmodel);
        jLabel1.setText("Mã đơn thuốc");
        jLabel2.setText("Số lượng");
        jLabel3.setText("Giá");
        jLabel4.setText("Mã hóa đơn");
        jLabel5.setText("Mã thuốc");
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel8.setText("Nhập mã đơn thuốc");
        jButton3.setText("Tìm đơn thuốc");
        jButton4.setText("Xóa đơn thuốc");
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(false);
        jTextField8.setVisible(true);
        jButton2.setText("Thêm đơn thuốc");
    }//GEN-LAST:event_jComboBox1ActionPerformed
     else if (selectedOption.equals("Thuốc, Dược Phẩm")) {
        jTable1.setModel(Tmodel);
        jLabel1.setText("Mã thuốc");
        jLabel2.setText("Tên thuốc");
        jLabel3.setText("Số lượng");
        jLabel4.setText("Giá thuốc");
        jLabel5.setText("Ngày sản xuất");
        jLabel6.setText("Hạn sử dụng");
        jLabel7.setText("Mã loại");
        jLabel8.setText("Nhập mã thuốc");
        jButton2.setText("Thêm thuốc");
        jButton3.setText("Tìm thuốc");
        jButton4.setText("Xóa thuốc");
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jTextField6.setVisible(true);
        jTextField7.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jTextField8.setVisible(true);
    }
    else if (selectedOption.equals("Khoa")) {
        jTable1.setModel(Kmodel);
        jLabel1.setText("Mã khoa");
        jLabel2.setText("Tên khoa");
        jLabel3.setText("Mô tả");
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel7.setText("");
        jButton2.setText("Thêm khoa");
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jButton2.setVisible(true);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jTextField8.setVisible(false);
        jLabel8.setText("");
    }
    else if (selectedOption.equals("Loại Thuốc")) {
        jTable1.setModel(LTmodel);
        jLabel1.setText("Mã loại");
        jLabel2.setText("Tên loại");
        jLabel3.setText("");
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel7.setText("");
        jButton2.setText("Thêm loại thuốc");
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jButton2.setVisible(true);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jLabel8.setText("");
    }
    else if (selectedOption.equals("Hóa Đơn")) {
        jTable1.setModel(HDmodel);
        jLabel1.setText("Mã hóa đơn");
        jLabel2.setText("Tiền tạm ứng");
        jLabel3.setText("Phí phát sinh");
        jLabel4.setText("Tiền khám");
        jLabel5.setText("Ngày lập");
        jLabel6.setText("Mã bệnh nhân");
        jLabel7.setText("");
        jLabel8.setText("Nhập mã hóa đơn");
        jButton2.setVisible(true);
        jTextField1.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jTextField4.setVisible(true);
        jTextField5.setVisible(true);
        jTextField6.setVisible(true);
        jTextField7.setVisible(false);
        jButton3.setVisible(true);
        jButton4.setVisible(false);
        jButton3.setText("Tìm hóa đơn");
        jButton4.setText("");
        jTextField8.setVisible(true);
        
    }
     else if (selectedOption.equals("Bệnh Án")) {
        jTable1.setModel(BAmodel);
        jLabel1.setText("");
        jLabel2.setText("");
        jLabel3.setText("");
        jLabel4.setText("");
        jLabel5.setText("");
        jLabel6.setText("");
        jLabel7.setText("");
        jLabel8.setText("Nhập mã bệnh án");
        jButton2.setText("");
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(true);
        jButton4.setVisible(false);
        jButton3.setText("Tìm bệnh án");
        jButton4.setText("");
        jTextField8.setVisible(true);
    }
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      String buttonText = jButton3.getText();
      String maTimKiem = jTextField8.getText().trim(); // Lấy giá trị từ JTextField và loại bỏ các khoảng trắng đầu và cuối

if (maTimKiem.isEmpty()) {
    // Nếu JTextField trống, hiển thị thông báo lỗi và không thực hiện bất kỳ hành động nào
    JOptionPane.showMessageDialog(this, "Vui lòng nhập mã để tìm kiếm hoặc xóa.", "Lỗi", JOptionPane.ERROR_MESSAGE);
} else {
    // Nếu không trống, thực hiện tìm kiếm và hiển thị kết quả
    DefaultTableModel searchModel = new DefaultTableModel();

    if (buttonText.equals("Tìm bác sĩ")) {
        table.findBS(searchModel, maTimKiem);
    } else if (buttonText.equals("Tìm bệnh nhân")) {
        table.findBN(searchModel, maTimKiem);
    } else if (buttonText.equals("Tìm hóa đơn")) {
        table.findHD(searchModel, maTimKiem);
    } else if (buttonText.equals("Tìm bệnh án")) {
        table.findBA(searchModel, maTimKiem);
    } else if (buttonText.equals("Tìm thuốc")) {
        table.findT(searchModel, maTimKiem);
    }

    // Hiển thị GUI mới với kết quả tìm kiếm
    search resultsGUI = new search(searchModel);
    resultsGUI.setVisible(true);
}


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       String buttonText = jButton4.getText();
       String maXoa = jTextField8.getText().trim(); // Lấy giá trị từ JTextField và loại bỏ các khoảng trắng đầu và cuối
    if (maXoa.isEmpty()) {
        // Nếu JTextField trống, hiển thị thông báo lỗi và không thực hiện bất kỳ hành động nào
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã để xóa.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (buttonText.equals("Xóa bác sĩ")) {
        table.deleteBS(maXoa);
        BSmodel.setRowCount(0);
        table.loadData1(BSmodel);
    } else if (buttonText.equals("Xóa bệnh nhân")) {
        table.deleteBN(maXoa);
        BNmodel.setRowCount(0);
        table.loadData2(BNmodel);
    } else if (buttonText.equals("Xóa thuốc")) {
        table.deleteBS(maXoa);
        Tmodel.setRowCount(0);
        table.loadData4(Tmodel);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        ThongKe thongKeGUI = new ThongKe();
        thongKeGUI.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login login = new login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       String selectedOption = jComboBox1.getSelectedItem().toString();
        if (selectedOption.equals("Bệnh Nhân")){
            BNmodel.setRowCount(0);
            table.loadData2(BNmodel);
         }
        if (selectedOption.equals("Bệnh Án")){
            BAmodel.setRowCount(0);
            table.loadData8(BAmodel);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        addSpecial ba = new addSpecial();
        ba.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
